### ISSUE TITLE
Luke 8.0.0: Error there is no IndexReader most functionalities are disabled

### ISSUE THREAD

**Issue by srssrs** [DmitryKey/luke#172]
I created the lucene indexes from scratch with Lucene 8.0.0. I'll try to visualize with luke 8.0.0 but I got the following message: "Directory opened. There is no IndexReader - most functionalities are disabled".

All tabs are disabled and no action is possible.

![Luke_Lucene_Toolbox_Project_v8_0_0](https://user-images.githubusercontent.com/6746414/55950183-9cd93680-5c54-11e9-9aa2-2ad54ee0897b.jpg)
 

Luke Version: 8.0.0
Lucene Version: 8.0.0

**Comment by mocobeta** [comment]
Hi, 
this is not an error. 
You open the index directory without an index reader but "directory reader". (The lower right cone icon shows that. This mode is used for repairing corrupted indexes and all index browsing functionality is disabled as the message says.)
**Uncheck** the [Expert options] > "Do not open IndexReader" check box in the "Open index" popup dialog and re-open the index so that you can browse or search the index.

**Comment by srssrs** [comment]
Ok it works. Thank you.
