### ISSUE TITLE
Allow copying from field values table

### ISSUE THREAD

**Issue by trejkaz** [DmitryKey/luke#45]
I can select rows in the field data table for a document, even multiple rows. But today I wanted a quick way to copy two rows out into a text file, and found that the usual ⌘C shortcut didn't copy the text.

If I right-click and show the full text, then copy from the text area in there, that does work, but since I'd like to do this for a few docs, it would have saved a lot of time had it just worked on the table.

Why it doesn't work is baffling. The default look and feel on OSX supports it without having to do anything, so initially I would assume the problem is with this weird look and feel being used in the application.

**Comment by mocobeta** [comment]
It is a very old issue about Thinlet Luke, but I have just re-visited it.

I think it would be much better to add something like "copy all stored values" button to copy all stored values to clipboard to Documents tab.
Now I cannot take time for this (have other issues to resolve,) but it is a good starting point for newbies who want to learn Lucene APIs. 
Could anyone take this?

**Comment by thrusc** [comment]
Hi, I would like to take this task.

**Comment by mocobeta** [comment]
@thrusc Thanks! Please, send a PR to the `master` branch. (If you have questions, feel free to ask us here.)

**Comment by thrusc** [comment]
I have some questions. What delimiter would be best for separation of values ? (new lines "\n" or some visible character like comma or semicolon) What should I do with null values ? (ignore them, use empty string or "null" value) It depends on use case, eg. using new lines and "null" - created string can be easealy pasted to excel, it will preserve number od values and it will devide each value to new cell in column.

**Comment by mocobeta** [comment]
> What delimiter would be best for separation of values ? (new lines "\n" or some visible character like comma or semicolon) 

First, we should decide the output file format. CSV(TSV) or JSON or XML are widely accepted, so I think it's preferable that we choose one of them. Stored values can contain arbitrary texts (may include commas, semicolons, line separators, any displayable characters.) To avoid escape character handling, I would use JSON or XML. If you have another proposal, please share this.

> new lines "\n"

Just in case, when handling new lines in Java you should always use `System.lineseparator()` instead of "\n". 
See: https://download.java.net/java/early_access/jdk11/docs/api/java.base/java/lang/System.html#lineSeparator()

> What should I do with null values ? (ignore them, use empty string or "null" value)

With Lucene index, null value means "there is no stored values available for the field". So we should simply ignore the field.
See: https://lucene.apache.org/core/7_5_0/core/org/apache/lucene/index/IndexableField.html

**Comment by thrusc** [comment]
I think best solution will be to create both.  Simple clipboard functionality for copy document values and create Export functionality with basic configuration eg. output file format, export one or multiple documents. They are both desirable and coverrige different use cases. Because if someone wants to get only values from document and he gets eg. JSON file he will be forced to process that file so it will be harder to extract values than simple paste it somewhere.

**Comment by mocobeta** [comment]
> I think best solution will be to create both. 
> They are both desirable and coverrige different use cases.

Agree, simple clipboard functionality to just "Copy & Paste" is handy for many situation.

> Is there any reason why it is not possible to select multiple rows at the same time? 

Of course, multiple rows selection is possible (it is just up to the JTable configuration.) In this case, I think we will have similar problem to "Copy all fields" functionality. Users can select arbitral multiple rows, so there will be fields with different names and values (those may contain commas, line separators... etc.)

More concretely, to implement simple "Copy & Paste" use case, we should handle 

- 

|field | value|
|----|-------|
|f1|apple<line separator>banana<grape>|
|f2|alice|
|f2|bob|

**Comment by mocobeta** [comment]
Sorry, my hands slipped.

**Comment by mocobeta** [comment]
It will be shipped with the next release, 7.5.0 (or 8.0.0).
